promotion:
    path:     /
    defaults: { _controller: "EmaRgementBundle:Promotion:index" }

promotion_show:
    path:     /{id}/show
    defaults: { _controller: "EmaRgementBundle:Promotion:show" }

promotion_new:
    path:     /new
    defaults: { _controller: "EmaRgementBundle:Promotion:new" }

promotion_create:
    path:     /create
    defaults: { _controller: "EmaRgementBundle:Promotion:create" }
    requirements: { _method: post }

promotion_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmaRgementBundle:Promotion:edit" }

promotion_update:
    path:     /{id}/update
    defaults: { _controller: "EmaRgementBundle:Promotion:update" }
    requirements: { _method: post|put }

promotion_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmaRgementBundle:Promotion:delete" }
    requirements: { _method: post|delete }
