ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }
example_homepage:
    path:     /example
    defaults: { _controller: EmaRgementBundle:Default:example }
ema_rgement_admin_panel:
    path:     /adminPanel
    defaults: { _controller: EmaRgementBundle:Default:adminPanel }