ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }
example_homepage:
    path:     /example
    defaults: { _controller: EmaRgementBundle:Default:example }
ema_rgement_admin_panel_user_list:
    path:     /admin/user/list
    defaults: { _controller: EmaRgementBundle:Default:adminUserList }
ema_rgement_admin_panel_configuration:
    path:     /admin/configuration
    defaults: { _controller: EmaRgementBundle:Default:adminConfiguration }