ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }

ema_rgement_dashboard:
    path:       /dashboard
    defaults:   { _controller: EmaRgementBundle:Default:dashboard }
