ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }

ema_rgement_dashboard:
    path:       /dashboard
    defaults:   { _controller: EmaRgementBundle:Default:dashboard }

example_homepage:
    path:     /example
    defaults: { _controller: EmaRgementBundle:Default:example }

ema_rgement_stats_accumulation_absence:
    path:     /stats/accumulation/absence
    defaults: { _controller: EmaRgementBundle:Default:statsAccumulationAbsence }

ema_rgement_stats_accumulation_delay:
    path:     /stats/accumulation/delay
    defaults: { _controller: EmaRgementBundle:Default:statsAccumulationDelay }

ema_rgement_stats_frequency_absence:
    path:     /stats/frequency/absence
    defaults: { _controller: EmaRgementBundle:Default:statsFrequencyAbsence }

ema_rgement_stats_frequency_delay:
    path:     /stats/frequency/delay
    defaults: { _controller: EmaRgementBundle:Default:statsFrequencyDelay }

ema_rgement_stats:
    path:     /stats/
    defaults: { _controller: EmaRgementBundle:Default:stats }

ema_rgement_warn_absence:
    path:     /warn/absence
    defaults: { _controller: EmaRgementBundle:Default:warnAbsence }

ema_rgement_warn_delay:
    path:     /warn/delay
    defaults: { _controller: EmaRgementBundle:Default:warnDelay }

ema_rgement_justify_list:
    path:     /justify/list
    defaults: { _controller: EmaRgementBundle:Default:justifyList }

ema_rgement_justify_absence:
    path:     /justify/absence
    defaults: { _controller: EmaRgementBundle:Default:justifyAbsence }

ema_rgement_justify_delay:
    path:     /justify/delay
    defaults: { _controller: EmaRgementBundle:Default:justifyDelay }

ema_rgement_admin_panel_user_list:
    path:     /admin/user/list
    defaults: { _controller: EmaRgementBundle:Default:adminUserList }

ema_rgement_admin_panel_configuration:
    path:     /admin/configuration
    defaults: { _controller: EmaRgementBundle:Default:adminConfiguration }

ema_rgement_tablette_eleves:
    path:     /tablette/eleves
    defaults: { _controller: EmaRgementBundle:Tablette:getEleves }

ema_rgement_tablette_first_force:
    path:     /tablette/first/force
    defaults: { _controller: EmaRgementBundle:Tablette:firstForce }

ema_rgement_tablette_first:
    path:     /tablette/first
    defaults: { _controller: EmaRgementBundle:Tablette:first }

ema_rgement_cron_update_first:
    path:     /cron/update/first
    defaults: { _controller: EmaRgementBundle:Cron:updateFirstJson }

ema_rgement_cron_update_all:
    path:     /cron/update/all
    defaults: { _controller: EmaRgementBundle:Cron:updateAll }

ema_rgement_cron_update_promotions:
    path:     /cron/update/promotions
    defaults: { _controller: EmaRgementBundle:Cron:updatePromotions }

ema_rgement_cron_update_etudiants:
    path:     /cron/update/etudiants
    defaults: { _controller: EmaRgementBundle:Cron:updateEtudiants }

ema_rgement_export:
    path:     /export
    defaults: { _controller: EmaRgementBundle:Default:export }

ema_rgement_report:
    path:     /report
    defaults: { _controller: EmaRgementBundle:Default:report }

ema_rgement_notification:
    path:     /notification
    defaults: { _controller: EmaRgementBundle:Default:notification }