ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }
example_homepage:
    path:     /example
    defaults: { _controller: EmaRgementBundle:Default:example }
warn_missing:
    path:     /warn/missing
    defaults: { _controller: EmaRgementBundle:Default:warnMissing }
justify_homepage:
    path:     /justify/list
    defaults: { _controller: EmaRgementBundle:Default:justifyList }