ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Report:list }

ema_rgement_dashboard:
    path:       /dashboard
    defaults:   { _controller: EmaRgementBundle:Default:dashboard }

example_homepage:
    path:     /example
    defaults: { _controller: EmaRgementBundle:Default:example }

ema_rgement_stats_accumulation_absence:
    path:     /stats/accumulation/absence
    defaults: { _controller: EmaRgementBundle:Default:statsAccumulationAbsence }

ema_rgement_stats_accumulation_delay:
    path:     /stats/accumulation/delay
    defaults: { _controller: EmaRgementBundle:Default:statsAccumulationDelay }

ema_rgement_stats_frequency_absence:
    path:     /stats/frequency/absence
    defaults: { _controller: EmaRgementBundle:Default:statsFrequencyAbsence }

ema_rgement_stats_frequency_delay:
    path:     /stats/frequency/delay
    defaults: { _controller: EmaRgementBundle:Default:statsFrequencyDelay }

ema_rgement_stats:
    path:     /stats/
    defaults: { _controller: EmaRgementBundle:Default:stats }

ema_rgement_warn_absence:
    path:     /warn/absence
    defaults: { _controller: EmaRgementBundle:Warn:warnAbsence }

ema_rgement_warn_delay:
    path:     /warn/delay
    defaults: { _controller: EmaRgementBundle:Warn:warnDelay }

ema_rgement_justify_list:
    path:     /justify/list
    defaults: { _controller: EmaRgementBundle:Justify:justifyList }

ema_rgement_ajax_list_absence_to_justify:
    path:     /justify/ajaxListAbsencesToJustify
    defaults: { _controller: EmaRgementBundle:Justify:ajaxListAbsencesToJustify }

ema_rgement_ajax_list_absence_to_justify_for_a_student:
    path:     /justify/ajaxListAbsencesToJustifyForAStudent
    defaults: { _controller: EmaRgementBundle:Justify:ajaxListAbsencesToJustifyForAStudent }

ema_rgement_justify_absence:
    path:     /justify/absence/{studentId}/{absenceId}
    defaults: { _controller: EmaRgementBundle:Justify:justifyAbsence, studentId null, absenceId null}

ema_rgement_justify_delay:
    path:     /justify/delay
    defaults: { _controller: EmaRgementBundle:Justify:justifyDelay }

ema_rgement_admin_panel_user_list:
    path:     /admin/user/list
    defaults: { _controller: EmaRgementBundle:Default:adminUserList }

ema_rgement_admin_panel_configuration:
    path:     /admin/configuration
    defaults: { _controller: EmaRgementBundle:Default:adminConfiguration }

ema_rgement_tablette_eleves:
    path:     /tablette/eleves
    defaults: { _controller: EmaRgementBundle:Tablette:getEleves }

ema_rgement_tablette_first_force:
    path:     /tablette/first/force
    defaults: { _controller: EmaRgementBundle:Tablette:firstForce }

ema_rgement_tablette_first:
    path:     /tablette/first
    defaults: { _controller: EmaRgementBundle:Tablette:first }

ema_rgement_tablette_set_data:
    path:     /tablette/set/data
    defaults: { _controller: EmaRgementBundle:Tablette:setDataCours }

ema_rgement_tablette_login:
    path:     /tablette/login
    defaults: { _controller: EmaRgementBundle:Tablette:login }

ema_rgement_cron_update_first:
    path:     /cron/update/first
    defaults: { _controller: EmaRgementBundle:Cron:updateFirstJson }

ema_rgement_cron_update_all:
    path:     /cron/update/all
    defaults: { _controller: EmaRgementBundle:Cron:updateAll }

ema_rgement_export_list:
    path:     /export/list
    defaults: { _controller: EmaRgementBundle:Export:list }

ema_rgement_ajax_list_exports:
    path:     /export/ajaxListExports
    defaults: { _controller: EmaRgementBundle:Export:ajaxListExports }

ema_rgement_export:
    path:     /export/studentId/{studentId}/promoId/{promoId}/from/{dateFrom}/to/{dateTo}
    defaults: { _controller: EmaRgementBundle:Export:export, studentId = 0, promoId = 0, dateFrom = null, dateTo = null }

ema_rgement_notification:
    path:     /notification/list
    defaults: { _controller: EmaRgementBundle:Notification:list }

ema_rgement_ajax_get_notification:
    path:     /notification/ajaxGetNotifications
    defaults: { _controller: EmaRgementBundle:Notification:ajaxGetNotifications }

ema_rgement_ajax_mark_all_the_notification_saw:
    path:     /notification/ajaxMarkAllTheNotificationsSaw
    defaults: { _controller: EmaRgementBundle:Notification:ajaxMarkAllTheNotificationsSaw }

ema_rgement_ajax_mark_a_notification_saw:
    path:     /notification/ajaxMarkANotificationSaw
    defaults: { _controller: EmaRgementBundle:Notification:ajaxMarkANotificationSaw }

ema_rgement_report_list:
    path:     report/
    defaults: { _controller: EmaRgementBundle:Report:list }

ema_rgement_report_show:
    path:     report/show/{id}
    defaults: { _controller: EmaRgementBundle:Report:show, id = 0}

ajax_synchronize_students_and_promos:
    path:     /admin/ajaxSynchronizeStudentsAndPromos
    defaults: { _controller: EmaRgementBundle:Admin:ajaxSynchronizeStudentsAndPromos }

ajax_synchronize_course :
    path:     /admin/ajaxSynchronizeCourses
    defaults: { _controller: EmaRgementBundle:Admin:ajaxSynchronizeCourses }
