ema_rgement_homepage:
    path:     /
    defaults: { _controller: EmaRgementBundle:Default:index }
ema_rgement_stats_accumulation_Absence:
    path:     /stats/accumulation/absence
    defaults: { _controller: EmaRgementBundle:Default:statsaccumulationAbsence }
ema_rgement_stats_accumulation_Delay:
    path:     /stats/accumulation/delay
    defaults: { _controller: EmaRgementBundle:Default:statsaccumulationDelay }
ema_rgement_stats_frequency_Absence:
    path:     /stats/frequency/absence
    defaults: { _controller: EmaRgementBundle:Default:statsfrequencyAbsence }
ema_rgement_stats_frequency_Delay:
    path:     /stats/frequency/delay
    defaults: { _controller: EmaRgementBundle:Default:statsfrequencyDelay }
ema_rgement_stats:
    path:     /stats/
    defaults: { _controller: EmaRgementBundle:Default:stats }
