services:
    justify_service:
        class: Ema\RgementBundle\Service\JustifyService
        calls:
            - [setContainer, ["@service_container"]]

    cron_controller_service:
        class: Ema\RgementBundle\Controller\CronController
        calls:
            - [setContainer, ["@service_container"]]
