#!/bin/bash
# This hook do some checks before pushing

# -- some variables / const init
VERT="\\033[1;32m"
NORMAL="\\033[0;39m"
JAUNE="\\033[1;33m"
ROUGE="\\033[1;31m"
current_status=0
final_status=0

# -- execution of all phpunit test on Soft
echo "** RUNNING UNIT TESTS **"
phpunit --colors --verbose --bootstrap tests/bootstrap.php --configuration tests/phpunit.xml tests/
if [ $? -gt 0 ]; then
    final_status=1
fi

if [ $final_status -eq 1 ]; then
    echo -e "$ROUGE" "Push failed, check your code" "$NORMAL"
fi
exit $final_status

