<?php

namespace Ema\RgementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends EntityRepository
{

    public function getByCourse($courseId)
    {
        $result = array();
//        $absence = new Absence();
//        $absence->setDateDebut(new \DateTime("now"));
//        $absence->setDateFin(new \DateTime("now"));
//        $absence->setMotif("MyMotif");
//        $result[] = $absence;
//        $absence = new Absence();
//        $absence->setDateDebut(new \DateTime("now"));
//        $absence->setDateFin(new \DateTime("now"));
//        $absence->setMotif("MyMotif2");
//        $result[] = $absence;
        return $result;
    }

}
