<?php

namespace Ema\RgementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM EmaRgementBundle:Promotion p'
            )
            ->getResult();
    }
    public function findById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM EmaRgementBundle:Promotion p WHERE p.id =$id'
            )
            ->getResult();
    }
}
