<?php

namespace Ema\RgementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipationAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationAbsenceRepository extends EntityRepository
{
}
