<?php

namespace Ema\RgementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardRepository extends EntityRepository
{

    public function getByCourse($courseId)
    {
        $result = array();
        $retard = new Retard();
        $retard->setDureeRetard(15);
        $result[] = $retard;
        $retard = new Retard();
        $retard->setDureeRetard(20);
        $result[] = $retard;
        return $result;
    }

}
