<?php

namespace Ema\RgementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardRepository extends EntityRepository
{
}
